### ISSUE TITLE
App not detected by Crashlytics

### ISSUE THREAD

**Issue by hpelitebook745G2** [corymsmith/react-native-fabric#119]
I have followed the instructions:
1. Installed the Fabric plugin in the Android Studio, created personal account in `fabrio.io`.
2. Installed `react-native-fabric` through `npm`
3. Did the following:
3.1. Edited `android/settings.gradle`
3.2. Edited `android/app/build.gradle`
3.3. Edited `MainApplication.java` in the application class since my react native version is `0.41.2`. Please look below:
`@Override
	  public void onCreate() {
		super.onCreate();
		Fabric.with(this, new Crashlytics()); // Added this line to fix the error ""
		SoLoader.init(this, /* native exopackage */ false);
	  }`

In my login screen I just wanted to test crash the app using `Crashlytics.crash();` of course I also initialized it globally with:
`var Fabric = require('react-native-fabric');
var { Crashlytics } = Fabric;`

Now the problem comes in, I'm now in login screen and when I pressed the Login button I encountered similar problem found [here](https://github.com/corymsmith/react-native-fabric/issues/99). Yet from what I understood in your reply, I configured it properly. But I want to crash it, not prompted by red error. What I did was to make a release build, and it successfully crashed when I pressed the button. So does this mean, I can only test Crashlytics with the release build?

My analysis, correct me if I'm wrong:
> Since the Fabric plugin is installed in the Android Studio and it is configured in the native code, the React Native layer (codes) are not detected by Fabric. 

So my problems are:
1. Is it correct to assume that I can't use or test Crashlytics with Debug mode? If not, did I miss any configuration?
2. Fabric plugin in my Android Studio can't detect my app even though I have added `android:name="io.fabric.ApiKey"` in the `AndroidManifest.xml`. I'm stuck in the `Launch your app!` stage from the Fabric plugin.
3. Now if I go to [https://fabric.io/dashboard](https://fabric.io/dashboard), I'm stuck with the Launch your app screen, also. I will be redirected to [https://fabric.io/onboard](https://fabric.io/onboard).

**Comment by asachin16** [comment]
I was having the same issue. In my case adding

`buildscript {
      repositories {
             maven { url 'https://maven.fabric.io/public' }
          }
       dependencies {
            // The Fabric Gradle plugin uses an open ended version to react
                     // quickly to Android tooling updates
                            classpath 'io.fabric.tools:gradle:1.+'
           }
     }
 apply plugin: 'io.fabric'`
to build.gradle worked

**Comment by corymsmith** [comment]
@asachin16's solution is the correct answer, closing this

**Comment by twairball** [comment]
@asachin16's solution is documented on repo as setup for **Android without Android Studio**. 

Can we clarify that these settings are still needed for Android Studio?

**Comment by voidstarfire** [comment]
Having same issue, @asachin16 which build.gradle files, there are multiple ones?

**Comment by iskWang** [comment]
my solution
* android/app/build.gradle
```
  apply plugin: "com.android.application"
  apply plugin: 'io.fabric'


{ ... }

dependencies {
   { ... }
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
}

{ ... }

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

```

**Comment by shoaibahmad** [comment]
![untitled](https://user-images.githubusercontent.com/1632202/34467541-dbd201a2-ef16-11e7-8618-f889c79e9167.png)
2017-12-21 18:32:23,269 [se-915-b01]   INFO - ols.intellij.CrashlyticsPlugin - Crashlytics 4.1.1 initialized for Android Studio 3.0 
2017-12-21 18:32:23,326 [d thread 2]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@7c341011 
2017-12-21 18:32:24,694 [se-915-b01]  DEBUG -                    Crashlytics - -------------Crashlytics appending to Intellij Logger------------- 
2017-12-21 18:32:24,728 [se-915-b01]   WARN -                    Crashlytics - Crashlytics was unable to completely start up. 
com.crashlytics.api.storage.exception.UnsupportedVersionException
	at com.crashlytics.api.storage.Hexifier.get(Hexifier.java:67)
	at com.crashlytics.api.RestfulWebApiCache.loadFromEncodedCache(RestfulWebApiCache.java:255)
	at com.crashlytics.api.RestfulWebApiCache.loadCachedOauthUser(RestfulWebApiCache.java:186)
	at com.crashlytics.api.RestfulWebApi.<init>(RestfulWebApi.java:180)
	at com.crashlytics.tools.intellij.core.CoreBundleActivator.init(CoreBundleActivator.java:278)
	at com.crashlytics.tools.intellij.core.CoreBundleActivator.start(CoreBundleActivator.java:140)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2154)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
	at com.crashlytics.tools.bootstrap.osgi.OsgiBootstrapper.loadComponents(OsgiBootstrapper.java:155)
	at com.crashlytics.tools.intellij.OSGiPluginServices.loadComponents(OSGiPluginServices.java:139)
	at com.crashlytics.tools.intellij.CrashlyticsPlugin.initComponent(CrashlyticsPlugin.java:90)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
	at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Please give me solution for this problem i have stuck on it for last many days
