### ISSUE TITLE
Crashlytics was unable to completely start up

### ISSUE THREAD

**Issue by shoaibahmad** [corymsmith/react-native-fabric#161]
![untitled](https://user-images.githubusercontent.com/1632202/34467574-c1e861f4-ef17-11e7-9b23-58899dc53311.png)

2017-12-21 18:32:23,269 [se-915-b01]   INFO - ols.intellij.CrashlyticsPlugin - Crashlytics 4.1.1 initialized for Android Studio 3.0 
2017-12-21 18:32:23,326 [d thread 2]   INFO - .openapi.application.Preloader - Finished preloading com.intellij.openapi.actionSystem.impl.ActionPreloader@7c341011 
2017-12-21 18:32:24,694 [se-915-b01]  DEBUG -                    Crashlytics - -------------Crashlytics appending to Intellij Logger------------- 
2017-12-21 18:32:24,728 [se-915-b01]   WARN -                    Crashlytics - Crashlytics was unable to completely start up. 
com.crashlytics.api.storage.exception.UnsupportedVersionException
	at com.crashlytics.api.storage.Hexifier.get(Hexifier.java:67)
	at com.crashlytics.api.RestfulWebApiCache.loadFromEncodedCache(RestfulWebApiCache.java:255)
	at com.crashlytics.api.RestfulWebApiCache.loadCachedOauthUser(RestfulWebApiCache.java:186)
	at com.crashlytics.api.RestfulWebApi.<init>(RestfulWebApi.java:180)
	at com.crashlytics.tools.intellij.core.CoreBundleActivator.init(CoreBundleActivator.java:278)
	at com.crashlytics.tools.intellij.core.CoreBundleActivator.start(CoreBundleActivator.java:140)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2154)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2072)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:976)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:963)
	at com.crashlytics.tools.bootstrap.osgi.OsgiBootstrapper.loadComponents(OsgiBootstrapper.java:155)
	at com.crashlytics.tools.intellij.OSGiPluginServices.loadComponents(OSGiPluginServices.java:139)
	at com.crashlytics.tools.intellij.CrashlyticsPlugin.initComponent(CrashlyticsPlugin.java:90)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
	at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Please give me any solution for this problem i have stuck on it for many days Thanks

**Comment by corymsmith** [comment]
This must be an issue with how you have Crashlytics in your project and not an issue with this library, closing.
