### ISSUE TITLE
Non-fatal Exception com.smixx.fabric.SMXCrashlytics.logException

### ISSUE THREAD

**Issue by NetPumi2** [corymsmith/react-native-fabric#181]
Hi we always have this error 
it is in Fabric library do you have some solution? 
we use v `"react-native-fabric": "0.5.1",`
```
Non-fatal Exception: java.lang.RuntimeException: Both onRight and rightTitle/rightButtonImage
            must be specified for the scene: article
       at com.smixx.fabric.SMXCrashlytics.logException(SMXCrashlytics.java:33)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:157)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by NetPumi2** [comment]
sorry depend on our project
