### ISSUE TITLE
Crashlytics.log don't logs into console on android, but on iOS

### ISSUE THREAD

**Issue by ColCh** [corymsmith/react-native-fabric#86]
it logs on iOS into console, but on android - not

from Crashlyrics support: http://support.crashlytics.com/knowledgebase/articles/120066-how-do-i-use-logging
> If you don't want to write to LogCat you should call 
> Crashlytics.log(msg) 

simply saying, it would be cool to log into console with Crashlytics.log

may be use LOG.Info by default? (https://developer.android.com/reference/android/util/Log.html#INFO)

**Comment by s2zaman** [comment]
Am getting something similar issue, that;
the `Crashlytics.logException('Test message');` for Android doesn't send a **string** message to Fabric. Instead it sends a too-long error in json format, which i don't need. I just need to send a simple string message.
However
the `Crashlytics.recordError('Test message');` does send a **string** message to Fabric.

**Snap of Android error**
- ![image](https://cloud.githubusercontent.com/assets/5410255/23304183/2f9948ec-faba-11e6-9beb-a8d86868092a.png)


**Snap of iOS error**
- ![image](https://cloud.githubusercontent.com/assets/5410255/23304270/be0662e0-faba-11e6-8c5b-f0ad5e2e29ce.png)

**It would be good, if there is any way to just send a simple string error to Fabric.**

**Comment by ColCh** [comment]
@s2zaman  Please take a look on this wrapper
https://gist.github.com/ColCh/d1daf4864a931faeb3d5c3d07917ebef
Example on `throw new Error(...)`:

IOS
![image](https://cloud.githubusercontent.com/assets/599439/23305049/f4818a46-faad-11e6-95af-06ad1092f63e.png)

android
![image](https://cloud.githubusercontent.com/assets/599439/23305060/03f672f2-faae-11e6-957d-0ace2879961d.png)

**Comment by ColCh** [comment]
@s2zaman  and a note how to translate error stacks to readable thing using source map:
https://github.com/corymsmith/react-native-fabric/issues/2#issuecomment-279140824

**Comment by s2zaman** [comment]
@ColCh yupp and Thanks for those points 👍 
But i need to send a plain string message Only. Still i will try to look for that.

**Comment by onpaws** [comment]
Been using `react-native-fabric` for a while and happy with it, thanks for your efforts guys.
Today I've been facing a difficult one.
My app crashes on launch, but only on a real device using a Release build. (Debug on Simulator works fine.)

![image](https://cloud.githubusercontent.com/assets/182515/23819213/3e4be9ea-05d1-11e7-841a-d4fa78335761.png)

@ColCh You've done some interesting work on this.
I tried using `require('./js/log.js')` in my `index.ios.js` as [suggested](https://gist.github.com/ColCh/d1daf4864a931faeb3d5c3d07917ebef) but still getting the minified stacktrace. 
Did I miss something?


============
RN 0.37
macOS 10.12.3
node 7.7.1

**Comment by ColCh** [comment]
It's reporting minified stacktrace - it's okay, at least to me...
I didn't managed to include sourcemap into app, because it will share source codes then.
And, to convert stacktrace to normal view on Crashlytics, stack-beautifier needs sourcemap file, and on RN there is no such possibility by-default.

**Comment by chitezh** [comment]
I have the same problem

```# Crashlytics - plaintext stacktrace downloaded by kingsley Ochu at Fri, 28 Apr 2017 07:47:21 GMT
# URL: https://fabric.io/tradedepot/android/apps/co.tradedepot.sfa/issues/5901c7c6be077a4dccfb5605?time=1493251200000%3A1493337599000/sessions/5902115C013B00012987A291C8E7FD51_45220680a6a14904b72129a9d75350d9_2_v1
# Organization: TradeDepot
# Platform: android
# Application: tradedepot retail
# Version: N/A
# Bundle Identifier: co.tradedepot.sfa
# Issue #: 39
# Issue ID: 5901c7c6be077a4dccfb5605
# Session ID: 5902115C013B00012987A291C8E7FD51_45220680a6a14904b72129a9d75350d9_2_v1
# Date: 2017-04-27T16:08:33Z
# OS Version: 6.0
# Device: Infinix HOT 4
# RAM Free: 33.3%
# Disk Free: 74.4%

#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at com.smixx.fabric.SMXCrashlytics.logException(SMXCrashlytics.java:33)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:207)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)

--

Non-fatal Exception: java.lang.RuntimeException: error: {"framesToPop":1,"code":"ENOENT"}
       at com.smixx.fabric.SMXCrashlytics.logException(SMXCrashlytics.java:33)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:207)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)

#0. Crashed: mqt_native_modules: 0 0 0x0000000000000000
       at com.smixx.fabric.SMXCrashlytics.logException(SMXCrashlytics.java:33)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:207)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```
