### ISSUE TITLE
ArrayIndexOutOfBoundsException: length=2; index=10 on Android

### ISSUE THREAD

**Issue by sibelius** [corymsmith/react-native-fabric#99]
```java
 java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
                                                                  at com.crashlytics.android.core.CrashTest.indexOutOfBounds(CrashTest.java:30)
                                                                  at com.crashlytics.android.core.CrashlyticsCore.crash(CrashlyticsCore.java:639)
                                                                  at com.crashlytics.android.Crashlytics.crash(Crashlytics.java:321)
                                                                  at com.smixx.fabric.SMXCrashlytics.crash(SMXCrashlytics.java:28)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
```

Fabric isn't recognizing my app

`Crashlytics.crash();` does not work

and I have the error above

From the logs, I see that Fabric is initializing correctly

```
01-28 07:04:16.501 20800-20800/net.app.br D/Fabric: Initializing io.fabric.sdk.android:fabric [Version: 1.3.10.97], with the following kits:
                                                       com.crashlytics.sdk.android:beta [Version: 1.1.4.92]
                                                       com.crashlytics.sdk.android:crashlytics [Version: 2.5.5.97]
                                                       com.crashlytics.sdk.android:answers [Version: 1.3.6.97]
                                                       com.crashlytics.sdk.android.crashlytics-core [Version: 2.3.8.97]

```

**Comment by corymsmith** [comment]
.crash() is supposed to crash your app so it's working correctly. You shouldn't be calling crash() unless you're trying to test crashing.

As you can see from the stack trace the crash is coming from the CrashTest class inside Crashlytics which means this lib is correctly calling through to the Native SDK and that you have that configured properly.

**Comment by lmj0011** [comment]
I fell for this too.
